#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
##    url: jdbc:postgresql://database-product-service:5432/postgres
#    url: jdbc:postgresql://localhost:5432/fitness_studio
#    username: postgres
##    password: root
#    password: pass
#  jpa:
#    show-sql: true
