mail:
  host: smtp.mail.ru
  port: 465
  username: ${MAIL_USER}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtps:
        starttls:
          enable: true
          required: true
        auth: true
        ssl: trust:smtp.mail.ru
  protocol: smtps