mail:
  host: smtp.mail.ru
  port: 465
  username: ${MAIL_USER}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtps:
        starttls:
          enable: true
          required: true
        auth: true
        ssl: trust:smtp.mail.ru
  protocol: smtps

spring:
  application:
    name: mail-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka