mail:
  host: smtp.mail.ru
  port: 465
  username: maksim.maks.23@mail.ru
  password: m8x7AeqawwuPHqybSrLQ
properties:
  mail:
    smtp:
      starttls:
        enable: true
        required: true
      auth: true
      ssl:
        trust:smtp.mail.ru