spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL_AUDIT}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
---
jpa:
  show-sql: true

hibernate:
  ddl-auto: none
jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}

