spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL_USER}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
---
spring:
  profiles: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fitness_studio
    username: postgres
    password: pass
---
jpa:
  show-sql: true
  hibernate:
    ddl-auto: none
jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
#  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
#  issuer: ITAcademy
mail:
  url: http://mail-service:8080/api/v1/mail/verification
audit:
  url: http://audit-service:8080/api/v1/audit/report