spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL_USER}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
---
jpa:
  show-sql: true
  hibernate:
    ddl-auto: none
jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
mail:
  url: http://mail-service:8080/api/v1/mail/verification
audit:
  url: http://audit-service:8080/api/v1/audit/report

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
    java:
      enabled: true
