spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL_USER}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
---
jpa:
  show-sql: true
  hibernate:
    ddl-auto: none
jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
mail:
  url: http://mail-service:8080/api/v1/mail/verification
audit:
  url: http://audit-service:8080/api/v1/audit/report

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metric
  info:
    contact:
      email: thymeleaf@thymeleaf.com
      phone: 822-625-6856
    env:
      enabled: true
    java:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka