spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL_PRODUCT}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
---
jpa:
  show-sql: true

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
audit:
  url: http://audit-service:8080/api/v1/audit/report

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka