spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db-product-service:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true

#    spring.mail.properties.mail.smtp.starttls.enable: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#    database: postgresql