spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-product-service:5432/postgres
    username: postgres
    password: root
---
#spring:
#  profiles: test
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/fitness_studio
#    username: postgres
#    password: pass
---
jpa:
  show-sql: true

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
audit:
  url: http://audit-service:8080/api/v1/audit/report